config/routes.rb
Mnygo::Application.routes.draw do
  match 'companies/reports/monthly_profits/:company_id' => 'reports#monthly_profits'
  match 'companies/reports/profits/:company_id' => 'reports#profits'
  match 'companies/reports/view_monthly_divisions/:company_id/:division_id' => 'reports#report_view_monthly_divisions'
  match 'companies/reports/monthly_divisions/:company_id' => 'reports#report_monthly_divisions'
  match 'companies/reports/divisions/:company_id' => 'reports#report_divisions'
  match 'companies/reports/view_monthly_locations/:company_id/:location_id' => 'reports#report_view_monthly_locations'
  match 'companies/reports/monthly_locations/:company_id' => 'reports#report_monthly_locations'
  match 'companies/reports/locations/:company_id' => 'reports#report_locations'
  match 'companies/reports/view_monthly_customers/:company_id/:customer_id' => 'reports#report_view_monthly_customers'
  match 'companies/reports/monthly_customers/:company_id' => 'reports#report_monthly_customers'
  match 'companies/reports/customers/:company_id' => 'reports#report_customers'
  match 'companies/reports/view_monthly_products/:company_id/:product_id' => 'reports#report_view_monthly_products'
  match 'companies/reports/monthly_products/:company_id' => 'reports#report_monthly_products'
  match 'companies/reports/products/:company_id' => 'reports#report_products'
  match 'companies/reports/view_monthly_sellers/:company_id/:user_id' => 'reports#report_view_monthly_sellers'
  match 'companies/reports/monthly_sellers/:company_id' => 'reports#report_monthly_sellers'
  match 'companies/reports/sellers/:company_id' => 'reports#report_sellers'
  match 'companies/reports/monthly_sales/:company_id' => 'reports#report_monthly_sales'
  match 'companies/reports/sales/:company_id' => 'reports#report_sales'
  match 'companies/reports/:company_id' => 'reports#reports'

  match 'company_users/ac_users' => 'company_users#ac_users'
  match 'company_users/new/:company_id' => 'company_users#new'
  match 'companies/company_users/:company_id' => 'company_users#list_users'
  resources :company_users

  match 'invoice/add_kit/:company_id' => 'invoices#add_kit'
  match 'invoices/list_items/:company_id' => 'invoices#list_items'
  match 'invoices/ac_kit/:company_id' => 'invoices#ac_kit'
  match 'invoices/ac_products/:company_id' => 'invoices#ac_products'
  match 'invoices/ac_user/:company_id' => 'invoices#ac_user'
  match 'invoices/ac_customers/:company_id' => 'invoices#ac_customers'
  match 'invoices/new/:company_id' => 'invoices#new'
  match 'invoices/do_email/:id' => 'invoices#do_email'
  match 'invoices/do_process/:id' => 'invoices#do_process'
  match 'invoices/email/:id' => 'invoices#email'
  match 'invoices/pdf/:id' => 'invoices#pdf'
  match 'companies/invoices/:company_id' => 'invoices#list_invoices'
  resources :invoices

  match 'customers/create_ajax/:company_id' => 'customers#create_ajax'
  match 'customers/new/:company_id' => 'customers#new'
  match 'companies/customers/:company_id' => 'customers#list_customers'
  resources :customers

  match 'divisions/new/:company_id' => 'divisions#new'
  match 'companies/divisions/:company_id' => 'divisions#list_divisions'
  resources :divisions

  match 'restocks/process/:id' => 'restocks#do_process'
  match 'restocks/new/:company_id/:product_id' => 'restocks#new'
  match 'companies/restocks/:company_id/:product_id' => 'restocks#list_restocks'
  resources :restocks

  match 'products_kits/list_items/:company_id' => 'products_kits#list_items'
  match 'products_kits/new/:company_id' => 'products_kits#new'
  match 'companies/products_kits/:company_id' => 'products_kits#list_products_kits'
  resources :products_kits

  match 'products_categories/new/:company_id' => 'products_categories#new'
  match 'companies/products_categories/:company_id' => 'products_categories#list_products_categories'
  resources :products_categories

  match 'products/ac_products/:company_id' => 'products#ac_products'
  match 'products/ac_categories/:company_id' => 'products#ac_categories'
  match 'products/new/:company_id' => 'products#new'
  match 'companies/products/:company_id' => 'products#list_products'
  resources :products

  match 'suppliers/new/:company_id' => 'suppliers#new'
  match 'companies/suppliers/:company_id' => 'suppliers#list_suppliers'
  resources :suppliers

  match 'locations/new/:company_id' => 'locations#new'
  match 'companies/locations/:company_id' => 'locations#list_locations'
  resources :locations
  
  match 'companies/export/:id' => 'companies#export'
  resources :companies

  resources :users_packages

  match 'payment/:slug' => 'packages#payment'
  match 'pricing/:slug' => 'packages#pick_package'
  match 'pricing' => 'packages#pricing'
  resources :packages

  match 'p/:page_name' => 'pages#name_clean'
  match 'err_not_found' => 'pages#err_not_found'
  match 'quick_upload' => 'pages#quick_upload'
  resources :pages

  match 'err_perms' => 'users#err_perms'
  match 'register' => 'users#register'
  match 'logout' => 'users#logout'
  match 'login' => 'users#login'
  resources :users
  
  resources :sessions
  
  match 'dashboard' => 'pages#dashboard'
  root :to => "pages#frontpage"
  

end

app/controllers/companies_controller.rb
include ApplicationHelper
include UsersHelper
include CompaniesHelper

class CompaniesController < ApplicationController
  before_filter :checkLogin
  
  # Export company to CSV
  def export
    @company = Company.find(params[:id])
    @customers = @company.get_customers()
    @divisions = @company.get_report_divisions()
    @locations = @company.get_report_locations()
    @products_categories = ProductsCategory.find(:all, :conditions => {:company_id => @company.id})
    @products = Product.find(:all, :conditions => {:company_id => @company.id})
    @suppliers = Supplier.find(:all, :conditions => {:company_id => @company.id})
    @products_kits = ProductsKit.find(:all, :conditions => {:company_id => @company.id})
    @invoices = Invoice.find(:all, :conditions => {:company_id => @company.id})
    @company_users = CompanyUser.find(:all, :conditions => {:company_id => @company.id})
    
    respond_to do |format|
      format.csv do
        render_csv("export_#{@company.id}")
      end
    end
  end
    
  # GET /companies
  # GET /companies.xml
  def index
    @pagetitle = 'My companies'
    @companies = getUser().get_companies()
    @user_package = UsersPackage.find(:first, :conditions => {:user_id => getUserId()})
    
    if(not @user_package)
      flash[:error] = 'Please first pick a pricing plan.'
      redirect_to '/pricing'
    end
  end

  # GET /companies/1
  # GET /companies/1.xml
  def show
    @company = Company.find(params[:id])
    set_company(@company)
    
    @pagetitle = @company[:name]
    @locations = Location.find(:all, :conditions => {:company_id => @company.id})
  end

  # GET /companies/new
  # GET /companies/new.xml
  def new
    @pagetitle = 'New company'
    @company = Company.new
    @company[:website] = 'http://'
    
    # Check package limits
    @companies_left_i = getUser().companies_left
    @companies_left = getUser().print_companies_left
    @companies_left_class = getUser().companies_left_class
  end

  # GET /companies/1/edit
  def edit
    @pagetitle = 'Edit company'
    @company = Company.find(params[:id])
    @edit = true
    
    if(not @company.own(getUser()))
      redirect_to '/err_perms'
    end
  end

  # POST /companies
  # POST /companies.xml
  def create
    @pagetitle = 'New company'
    @company = Company.new(params[:company])
    @company[:user_id] = getUserId()
    
    @companies_left_i = getUser().companies_left
    @companies_left = getUser().print_companies_left
    @companies_left_class = getUser().companies_left_class
    
    # Check package limits
    if(@companies_left_i <= 0 and @companies_left_i > -1000)
      flash[:error] = "You have created the most companies you can within your package.  Please select another package to create more companies."
      redirect_to("/pricing")
    else
      respond_to do |format|
        # Should we upload a logo?
        if(params[:company][:logo])
          if(not checkFileExtension(params[:company][:logo], imgTypes()))
            flash[:error] = "The logo you tried to upload doesn't have the correct format.  Please upload a GIF, JPG, or PNG image."
            format.html { render :action => "edit" }
          else
            params[:company][:logo] = @company.upload_logo(params[:company][:logo])
          end
        end

        if @company.save
          # Create company user for the user
          new_company_user = CompanyUser.new(:company_id => @company.id, :user_id => getUserId())
          new_company_user.save

          format.html { redirect_to(@company, :notice => 'Company was successfully created.') }
          format.xml  { render :xml => @company, :status => :created, :location => @company }
        else
          format.html { render :action => "new" }
          format.xml  { render :xml => @company.errors, :status => :unprocessable_entity }
        end
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.xml
  def update
    @pagetitle = 'Edit company'
    @company = Company.find(params[:id])

    respond_to do |format|
      # Should we upload a logo?
      if(params[:company][:logo])
        if(not checkFileExtension(params[:company][:logo], imgTypes()))
          flash[:error] = "The logo you tried to upload doesn't have the correct format.  Please upload a GIF, JPG, or PNG image."
          format.html { render :action => "edit" }
        else
          params[:company][:logo] = @company.upload_logo(params[:company][:logo])
        end
      end
      
      if @company.update_attributes(params[:company])
        format.html { redirect_to(@company, :notice => 'Company was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @company.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.xml
  def destroy
    @company = Company.find(params[:id])
    
    if(not @company.own(getUser()))
      redirect_to '/err_perms'
    else
      @company_users = CompanyUser.find(:all, :conditions => {:company_id => @company.id})
      
      for cu in @company_users
        cu.destroy
      end
      
      @company.delete_logo()
      @company.destroy

      redirect_to(companies_url)
    end
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
  def set_company(company)
    session[:company] = company
  end
  
  def get_session_company()
    if(isLogged() and session[:company])
      return session[:company]
    end
  end
  
  def checkCompanies()
    if(isLogged())
      company = Company.find(:first, :conditions => {:user_id => getUserId()})
      
      if not company
        flash[:error] = "Please create a company first."
        redirect_to "/companies/new"
      end
    end
  end
end

app/views/companies/_form.html.erb
<%= form_for(@company, :html => {:multipart => true}) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :name, 'Company name*', :class => 'bold' %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :logo %><br />
    <%= f.file_field :logo %>
  </div>
  <div class="field">
    <%= f.label :address1, 'Address 1' %><br />
    <%= f.text_field :address1 %>
  </div>
  <div class="field">
    <%= f.label :address2, 'Address 2' %><br />
    <%= f.text_field :address2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip, 'ZIP/Postal Code' %><br />
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <% if @edit %>
      <%= f.select :country, countries_array %>
    <% else %>
      <%= f.select :country, options_for_select(countries_array, "United States") %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :phone1, 'Phone 1' %><br />
    <%= f.text_field :phone1 %>
  </div>
  <div class="field">
    <%= f.label :phone2, 'Phone 2' %><br />
    <%= f.text_field :phone2 %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/_list.html.erb
<p>
  Select a company to add products, create invoices, process orders, etc.
</p>

<% if @companies.count > 0 %>
  <div class="companies">
    <% for company in @companies %>
      <div class="item">
        <div class="title">
          <%= link_to company.name, company %>
        </div>
        <div class="metadata">
          <%= link_to "View", company %>
          <% if(company.own(@session_user)) %>
            &#183;
            <%= link_to "Edit", edit_company_path(company) %> &#183;
            <%= link_to "Delete", company, :confirm => 'Are you sure?', :method => :delete %>
          <% end %>
        </div>
        <%= br() %>
      </div>
    <% end %>
  </div>
<% else %>
  <p class="error">
    You have not yet created any companies.  You can <%= link_to "create one", "/companies/new" %> now.
  </p>
<% end %>

<div class="button">
  <%= link_to "New company", "/companies/new" %>
</div>

app/views/companies/_list_select.html.erb
<% if @companies %>
  <div class="companies">
    <% for company in @companies %>
      <div class="item">
        <div class="title">
          <%= link_to company.name, "/companies/#{@path}/#{company.id}" %>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <p class="error">
    You have not yet created any companies.  You can <%= link_to "create one", "/companies/new" %> now.
  </p>
<% end %>

app/views/companies/edit.html.erb
<div class="breadcrumbs">
  <%= link_to "My companies", "/companies" %>
</div>

<h1>
  <%= image_tag("company_48.png", :class => "vmiddle") %>
  Edit company
</h1>

<p>
  To create modify a company, please fill out the following form.  Fields marked with <strong>*</strong> are required.
</p>

<%= render 'form' %>

<div class="button">
  <%= link_to 'View', @company %>
  <%= link_to 'Back', companies_path %>
</div>

app/views/companies/export.csv.erb
============================================================
Company information
============================================================
id,name,address1,address2,city,state,zip,country,website,phone1,phone2,email,created_at,updated_at
<%= "#{@company.id.format_csv},#{@company.name.format_csv},#{@company.address1.format_csv},#{@company.address2.format_csv},#{@company.city.format_csv},#{@company.state.format_csv},#{@company.zip.format_csv
},#{@company.country.format_csv},#{@company.website.format_csv},#{@company.phone1.format_csv},#{@company.phone2.format_csv},#{@company.email.format_csv},#{@company.created_at.format_csv},#{@company.updated_at.format_csv}" %>

============================================================
Customers
============================================================
id,name,email,phone1,phone2,address1,address2,city,state,zip,country,comments,account,taxable,created_at,updated_at
<% for customer in @customers %>
<%= "#{customer.id.format_csv},#{customer.name.format_csv},#{customer.email.format_csv},#{customer.phone1.format_csv},#{customer.phone2.format_csv},#{customer.address1.format_csv},#{customer.address2.format_csv},#{customer.city.format_csv},#{customer.state.format_csv},#{customer.zip.format_csv},#{customer.country.format_csv},#{customer.comments.format_csv},#{customer.account.format_csv},#{customer.taxable.format_csv},#{customer.created_at.format_csv},#{customer.updated_at.format_csv}" %>
<% end %>

============================================================
Locations
============================================================
id,name,address1,address2,city,state,zip,country,website,phone1,phone2,email,created_at,updated_at
<% for location in @locations %>
<%= "#{location.id.format_csv},#{location.name.format_csv},#{location.address1.format_csv},#{location.address2.format_csv},#{location.city.format_csv},#{location.state.format_csv},#{location.zip.format_csv},#{location.country.format_csv},#{location.website.format_csv},#{location.phone1.format_csv},#{location.phone2.format_csv},#{location.email.format_csv},#{location.created_at.format_csv},#{location.updated_at.format_csv}" %>
<% end %>

============================================================
Divisions
============================================================
id,location_id,name,description,created_at,updated_at
<% for division in @divisions %>
<%= "#{division.id.format_csv},#{division.location_id.format_csv},#{division.name.format_csv},#{division.description.format_csv},#{customer.created_at.format_csv},#{customer.updated_at.format_csv}" %>
<% end %>

============================================================
Product categories
============================================================
id,category,created_at,updated_at
<% for category in @products_categories %>
<%= "#{category.id.format_csv},#{category.category.format_csv},#{customer.created_at.format_csv},#{customer.updated_at.format_csv}" %>
<% end %>

============================================================
Suppliers
============================================================
id,name,email,phone1,phone2,address1,address2,city,state,zip,country,comments,created_at,updated_at
<% for supplier in @suppliers %>
<%= "#{supplier.id.format_csv},#{supplier.name.format_csv},#{supplier.email.format_csv},#{supplier.phone1.format_csv},#{supplier.phone2.format_csv},#{supplier.address1.format_csv},#{supplier.address2.format_csv},#{supplier.city.format_csv},#{supplier.state.format_csv},#{supplier.zip.format_csv},#{supplier.country.format_csv},#{supplier.comments.format_csv},#{supplier.created_at.format_csv},#{supplier.updated_at.format_csv}" %>
<% end %>

============================================================
Product kits
============================================================
id,name,description,created_at,updated_at
<% for kit in @products_kits %>
<%= "#{kit.id.format_csv},#{kit.name.format_csv},#{kit.description.format_csv},#{kit.created_at.format_csv},#{kit.updated_at.format_csv}" %>
<% end %>

============================================================
Products in product kits
============================================================
id,product_kit_id,product_id,quantity,created_at,updated_at
<% for kit in @products_kits %>
<% for kp in kit.get_kits_products() %>
<%= "#{kp.id.format_csv},#{kp.product_kit_id.format_csv},#{kp.product_id.format_csv},#{kp.quantity.format_csv},#{kp.created_at.format_csv},#{kit.updated_at.format_csv}" %>
<% end %>
<% end %>

============================================================
Users
============================================================
id,username,email,first_name,last_name,created_at,updated_at
<% for company_user in @company_users %>
<%= "#{company_user.user.id.format_csv},#{company_user.user.username.format_csv},#{company_user.user.email.format_csv},#{company_user.user.first_name.format_csv},#{company_user.user.last_name.format_csv},#{company_user.user.created_at.format_csv},#{company_user.user.updated_at.format_csv}" %>
<% end %>

============================================================
Invoices
============================================================
id,location_id,division_id,customer_id,description,comments,code,subtotal,tax,total,processed,return,date_processed,user_id,created_at,updated_at
<% for invoice in @invoices %>
<%= "#{invoice.id.format_csv},#{invoice.location_id.format_csv},#{invoice.division_id.format_csv},#{invoice.customer_id.format_csv},#{invoice.description.format_csv},#{invoice.comments.format_csv},#{invoice.code.format_csv},#{invoice.subtotal.format_csv},#{invoice.tax.format_csv},#{invoice.total.format_csv},#{invoice.processed.format_csv},#{invoice.return.format_csv},#{invoice.date_processed.format_csv},#{invoice.user_id.format_csv},#{invoice.created_at.format_csv},#{invoice.updated_at.format_csv}" %>
<% end %>

============================================================
Invoice products
============================================================
id,invoice_id,product_id,price,quantity,discount,total,created_at,updated_at
<% for invoice in @invoices %>
<% for ip in invoice.get_invoice_products %>
<%= "#{ip.id.format_csv},#{ip.invoice_id.format_csv},#{ip.product_id.format_csv},#{ip.price.format_csv},#{ip.quantity.format_csv},#{ip.discount.format_csv},#{ip.total.format_csv},#{ip.created_at.format_csv},#{ip.updated_at.format_csv}," %>
<% end %>
<% end %>

app/views/companies/index.html.erb
<h1>
  <%= image_tag("company_48.png", :class => "vmiddle") %>
  My companies
</h1>

<%= render 'companies/list' %>

app/views/companies/new.html.erb
<div class="breadcrumbs">
  <%= link_to "My companies", "/companies" %>
</div>

<h1>
  <%= image_tag("company_48.png", :class => "vmiddle") %>
  New company
</h1>

<div class="<%= @companies_left_class %>">
  You can create <%= @companies_left %> more companies.
  <% if @companies_left_i <= 0 and @companies_left_i != -1000 %>
    If you want to create more companies, please <%= link_to "select another package", "/pricing" %>.
  <% end %>
</div>

<p>
  To create a new company, please fill out the following form.  Fields marked with <strong>*</strong> are required.
</p>

<%= render 'form' %>

<div class="button">
  <%= link_to 'Back', companies_path %>
</div>

app/views/companies/show.html.erb
<div class="breadcrumbs">
  <%= link_to "My companies", "/companies" %>
</div>

<h1>
  <%= image_tag("company_48.png", :class => "vmiddle") %>
  <%= @company.name %>
</h1>

<%= hr() %>

<div class="mid_box bordered_right">
  <h3>
    <%= image_tag("products_32.png", :class => "vmiddle") %>
    <%= link_to "Products", "/companies/products/#{@company.id}" %>
  </h3>

  <p>
    Add, edit or delete the products or services your company offers.
  </p>

  <%= hr() %>

  <h3>
    <%= image_tag("product_kit_32.png", :class => "vmiddle") %>
    <%= link_to "Product kits", "/companies/products_kits/#{@company.id}" %>
  </h3>

  <p>
    Add, edit or delete product kits (groups of products).
  </p>

  <%= hr() %>

  <h3>
    <%= image_tag("product_category_32.png", :class => "vmiddle") %>
    <%= link_to "Product categories", "/companies/products_categories/#{@company.id}" %>
  </h3>

  <p>
    Add, edit or delete the categories for your products.
  </p>

  <%= hr() %>

  <h3>
    <%= image_tag("invoice_32.png", :class => "vmiddle") %>
    <%= link_to "Invoices", "/companies/invoices/#{@company.id}" %>
  </h3>

  <p>
    Add, edit or delete invoices for your business.
  </p>
  
  <%= hr() %>
  
  <h3>
    <%= image_tag("employees_32.png", :class => "vmiddle") %>
    <%= link_to "Users", "/companies/company_users/#{@company.id}" %>
  </h3>

  <p>
    Add, edit or delete users that have access to your company.
  </p>
</div>

<div class="mid_box">
  <h3>
    <%= image_tag("clients_32.png", :class => "vmiddle") %>
    <%= link_to "Customers", "/companies/customers/#{@company.id}" %>
  </h3>

  <p>
    Add, edit or delete customers for your business.
  </p>

  <%= hr() %>

  <h3>
    <%= image_tag("supplier_32.png", :class => "vmiddle") %>
    <%= link_to "Suppliers", "/companies/suppliers/#{@company.id}" %>
  </h3>

  <p>
    Add, edit or delete suppliers for your business.
  </p>

  <%= hr() %>

  <h3>
    <%= image_tag("locations_32.png", :class => "vmiddle") %>
    <%= link_to "Locations", "/companies/locations/#{@company.id}" %>
  </h3>

  <p>
    Add, edit or delete your company's locations, branches, offices or subsidiaries.
  </p>

  <%= hr() %>

  <h3>
    <%= image_tag("divisions_32.png", :class => "vmiddle") %>
    <%= link_to "Divisions", "/companies/divisions/#{@company.id}" %>
  </h3>

  <p>
    Add, edit or delete your company's divisions (tables, sections, etc).
  </p>
  
  <%= hr() %>
  
  <h3>
    <%= image_tag("reports_32.png", :class => "vmiddle") %>
    <%= link_to "Reports", "/companies/reports/#{@company.id}" %>
  </h3>

  <p>
    Add, edit or delete your company's divisions (tables, sections, etc).
  </p>
</div>

<%= br() %>
<%= hr() %>

<% if @company.logo %>
  <div class="company_logo">
    <img src="<%= img_name_size(@company.logo, 200) %>" alt="Logo" />
  </div>
<% end %>

<h3>
  Company info
</h3>

<p>
  <strong>Owner:</strong>
  <%= @company.user.print.html_safe %>
</p>

<% if @company.address1 != "" %>
  <p>
    <b>Address1:</b>
    <%= @company.address1 %>
  </p>
<% end %>

<% if @company.address2 != "" %>
  <p>
    <b>Address2:</b>
    <%= @company.address2 %>
  </p>
<% end %>

<% if @company.city != "" %>
  <p>
    <b>City:</b>
    <%= @company.city %>
  </p>
<% end %>

<% if @company.state != "" %>
  <p>
    <b>State:</b>
    <%= @company.state %>
  </p>
<% end %>

<% if @company.zip != "" %>
  <p>
    <b>Zip:</b>
    <%= @company.zip %>
  </p>
<% end %>

<% if @company.country != "" %>
  <p>
    <b>Country:</b>
    <%= @company.country %>
  </p>
<% end %>

<% if @company.website != "" and @company.website != "http://" %>
  <p>
    <b>Website:</b>
    <%= @company.website %>
  </p>
<% end %>

<% if @company.phone1 != "" %>
  <p>
    <b>Phone1:</b>
    <%= @company.phone1 %>
  </p>
<% end %>

<% if @company.phone2 != "" %>
  <p>
    <b>Phone2:</b>
    <%= @company.phone2 %>
  </p>
<% end %>

<% if @company.email != "" %>
  <p>
    <b>Email:</b>
    <%= @company.email %>
  </p>
<% end %>

<%= br() %>

<div class="button">
  <% if @company.own(@session_user) %>
    <%= link_to 'Edit', edit_company_path(@company) %>
    <%= link_to 'Export data to Excel', "/companies/export/#{@company.id}.csv" %>
  <% end %>

  <%= link_to 'Back', companies_path %>
</div>