config/routes.rb
Mnygo::Application.routes.draw do
  match 'companies/reports/monthly_profits/:company_id' => 'reports#monthly_profits'
  match 'companies/reports/profits/:company_id' => 'reports#profits'
  match 'companies/reports/view_monthly_divisions/:company_id/:division_id' => 'reports#report_view_monthly_divisions'
  match 'companies/reports/monthly_divisions/:company_id' => 'reports#report_monthly_divisions'
  match 'companies/reports/divisions/:company_id' => 'reports#report_divisions'
  match 'companies/reports/view_monthly_locations/:company_id/:location_id' => 'reports#report_view_monthly_locations'
  match 'companies/reports/monthly_locations/:company_id' => 'reports#report_monthly_locations'
  match 'companies/reports/locations/:company_id' => 'reports#report_locations'
  match 'companies/reports/view_monthly_customers/:company_id/:customer_id' => 'reports#report_view_monthly_customers'
  match 'companies/reports/monthly_customers/:company_id' => 'reports#report_monthly_customers'
  match 'companies/reports/customers/:company_id' => 'reports#report_customers'
  match 'companies/reports/view_monthly_products/:company_id/:product_id' => 'reports#report_view_monthly_products'
  match 'companies/reports/monthly_products/:company_id' => 'reports#report_monthly_products'
  match 'companies/reports/products/:company_id' => 'reports#report_products'
  match 'companies/reports/view_monthly_sellers/:company_id/:user_id' => 'reports#report_view_monthly_sellers'
  match 'companies/reports/monthly_sellers/:company_id' => 'reports#report_monthly_sellers'
  match 'companies/reports/sellers/:company_id' => 'reports#report_sellers'
  match 'companies/reports/monthly_sales/:company_id' => 'reports#report_monthly_sales'
  match 'companies/reports/sales/:company_id' => 'reports#report_sales'
  match 'companies/reports/:company_id' => 'reports#reports'

  match 'company_users/ac_users' => 'company_users#ac_users'
  match 'company_users/new/:company_id' => 'company_users#new'
  match 'companies/company_users/:company_id' => 'company_users#list_users'
  resources :company_users

  match 'invoice/add_kit/:company_id' => 'invoices#add_kit'
  match 'invoices/list_items/:company_id' => 'invoices#list_items'
  match 'invoices/ac_kit/:company_id' => 'invoices#ac_kit'
  match 'invoices/ac_products/:company_id' => 'invoices#ac_products'
  match 'invoices/ac_user/:company_id' => 'invoices#ac_user'
  match 'invoices/ac_customers/:company_id' => 'invoices#ac_customers'
  match 'invoices/new/:company_id' => 'invoices#new'
  match 'invoices/do_email/:id' => 'invoices#do_email'
  match 'invoices/do_process/:id' => 'invoices#do_process'
  match 'invoices/email/:id' => 'invoices#email'
  match 'invoices/pdf/:id' => 'invoices#pdf'
  match 'companies/invoices/:company_id' => 'invoices#list_invoices'
  resources :invoices

  match 'customers/create_ajax/:company_id' => 'customers#create_ajax'
  match 'customers/new/:company_id' => 'customers#new'
  match 'companies/customers/:company_id' => 'customers#list_customers'
  resources :customers

  match 'divisions/new/:company_id' => 'divisions#new'
  match 'companies/divisions/:company_id' => 'divisions#list_divisions'
  resources :divisions

  match 'restocks/process/:id' => 'restocks#do_process'
  match 'restocks/new/:company_id/:product_id' => 'restocks#new'
  match 'companies/restocks/:company_id/:product_id' => 'restocks#list_restocks'
  resources :restocks

  match 'products_kits/list_items/:company_id' => 'products_kits#list_items'
  match 'products_kits/new/:company_id' => 'products_kits#new'
  match 'companies/products_kits/:company_id' => 'products_kits#list_products_kits'
  resources :products_kits

  match 'products_categories/new/:company_id' => 'products_categories#new'
  match 'companies/products_categories/:company_id' => 'products_categories#list_products_categories'
  resources :products_categories

  match 'products/ac_products/:company_id' => 'products#ac_products'
  match 'products/ac_categories/:company_id' => 'products#ac_categories'
  match 'products/new/:company_id' => 'products#new'
  match 'companies/products/:company_id' => 'products#list_products'
  resources :products

  match 'suppliers/new/:company_id' => 'suppliers#new'
  match 'companies/suppliers/:company_id' => 'suppliers#list_suppliers'
  resources :suppliers

  match 'locations/new/:company_id' => 'locations#new'
  match 'companies/locations/:company_id' => 'locations#list_locations'
  resources :locations
  
  match 'companies/export/:id' => 'companies#export'
  resources :companies

  resources :users_packages

  match 'payment/:slug' => 'packages#payment'
  match 'pricing/:slug' => 'packages#pick_package'
  match 'pricing' => 'packages#pricing'
  resources :packages

  match 'p/:page_name' => 'pages#name_clean'
  match 'err_not_found' => 'pages#err_not_found'
  match 'quick_upload' => 'pages#quick_upload'
  resources :pages

  match 'err_perms' => 'users#err_perms'
  match 'register' => 'users#register'
  match 'logout' => 'users#logout'
  match 'login' => 'users#login'
  resources :users
  
  resources :sessions
  
  match 'dashboard' => 'pages#dashboard'
  root :to => "pages#frontpage"
  

end

app/models/users_package.rb
class UsersPackage < ActiveRecord::Base
  validates_uniqueness_of :user_id
  
  belongs_to :user
  belongs_to :package
end

app/controllers/users_packages_controller.rb
include UsersHelper

class UsersPackagesController < ApplicationController
  before_filter :checkAdmin
  
  # GET /users_packages
  # GET /users_packages.xml
  def index
    @pagetitle = "User packages"
    
    @users_packages = UsersPackage.all
  end

  # GET /users_packages/1
  # GET /users_packages/1.xml
  def show
    @pagetitle = "View user package"
    
    @users_package = UsersPackage.find(params[:id])
  end

  # GET /users_packages/new
  # GET /users_packages/new.xml
  def new
    @pagetitle = "New user package"
    
    @users_package = UsersPackage.new
    @packages = Package.find(:all)
  end

  # GET /users_packages/1/edit
  def edit
    @pagetitle = "Edit user package"
    
    @users_package = UsersPackage.find(params[:id])
    @packages = Package.find(:all)
  end

  # POST /users_packages
  # POST /users_packages.xml
  def create
    @pagetitle = "New user package"
    
    @users_package = UsersPackage.new(params[:users_package])
    @packages = Package.find(:all)

    respond_to do |format|
      if @users_package.save
        format.html { redirect_to(@users_package, :notice => 'Users package was successfully created.') }
        format.xml  { render :xml => @users_package, :status => :created, :location => @users_package }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @users_package.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users_packages/1
  # PUT /users_packages/1.xml
  def update
    @pagetitle = "Edit user package"
    
    @users_package = UsersPackage.find(params[:id])
    @packages = Package.find(:all)

    respond_to do |format|
      if @users_package.update_attributes(params[:users_package])
        format.html { redirect_to(@users_package, :notice => 'Users package was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @users_package.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users_packages/1
  # DELETE /users_packages/1.xml
  def destroy
    @users_package = UsersPackage.find(params[:id])
    @users_package.destroy

    respond_to do |format|
      format.html { redirect_to(users_packages_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/users_packages_helper.rb
module UsersPackagesHelper
end

app/views/users_packages/_form.html.erb
<%= form_for(@users_package) do |f| %>
  <% if @users_package.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@users_package.errors.count, "error") %> prohibited this users_package from being saved:</h2>

      <ul>
      <% @users_package.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :package_id %><br />
    <%= f.select :package_id, @packages.map {|p| [p.title, p.id]} %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.date_select :end_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users_packages/edit.html.erb
<div class="breadcrumbs">
  <%= link_to "Users packages", users_packages_path %>
</div>

<h1>
  Editing users_package
</h1>

<%= render 'form' %>

<div class="button">
  <%= link_to 'Show', @users_package %>
  <%= link_to 'Back', users_packages_path %>
</div>

app/views/users_packages/index.html.erb
<h1>
  Users_packages
</h1>

<table>
  <tr>
    <th>User</th>
    <th>Package</th>
    <th>Start date</th>
    <th>End date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users_packages.each do |users_package| %>
  <tr>
    <td><%= users_package.user.print.html_safe %></td>
    <td><%= users_package.package_id %></td>
    <td><%= doDate(users_package.start_date, 3) %></td>
    <td><%= doDate(users_package.end_date, 3) %></td>
    <td><%= link_to 'Show', users_package %></td>
    <td><%= link_to 'Edit', edit_users_package_path(users_package) %></td>
    <td><%= link_to 'Destroy', users_package, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<div class="button">
  <%= link_to 'New Users package', new_users_package_path %>
</div>

app/views/users_packages/new.html.erb
<div class="breadcrumbs">
  <%= link_to "Users packages", users_packages_path %>
</div>

<h1>
  New users_package
</h1>

<%= render 'form' %>

<div class="button">
  <%= link_to 'Back', users_packages_path %>
</div>

app/views/users_packages/show.html.erb
<p>
  <b>User:</b>
  <%= @users_package.user.print.html_safe %>
</p>

<p>
  <b>Package:</b>
  <%= @users_package.package_id %>
</p>

<p>
  <b>Start date:</b>
  <%= doDate(@users_package.start_date, 3) %>
</p>

<p>
  <b>End date:</b>
  <%= doDate(@users_package.end_date, 3) %>
</p>

<div class="button">
  <%= link_to 'Edit', edit_users_package_path(@users_package) %>
  <%= link_to 'Back', users_packages_path %>
</div>