config/routes.rb
Mnygo::Application.routes.draw do
  match 'companies/reports/monthly_profits/:company_id' => 'reports#monthly_profits'
  match 'companies/reports/profits/:company_id' => 'reports#profits'
  match 'companies/reports/view_monthly_divisions/:company_id/:division_id' => 'reports#report_view_monthly_divisions'
  match 'companies/reports/monthly_divisions/:company_id' => 'reports#report_monthly_divisions'
  match 'companies/reports/divisions/:company_id' => 'reports#report_divisions'
  match 'companies/reports/view_monthly_locations/:company_id/:location_id' => 'reports#report_view_monthly_locations'
  match 'companies/reports/monthly_locations/:company_id' => 'reports#report_monthly_locations'
  match 'companies/reports/locations/:company_id' => 'reports#report_locations'
  match 'companies/reports/view_monthly_customers/:company_id/:customer_id' => 'reports#report_view_monthly_customers'
  match 'companies/reports/monthly_customers/:company_id' => 'reports#report_monthly_customers'
  match 'companies/reports/customers/:company_id' => 'reports#report_customers'
  match 'companies/reports/view_monthly_products/:company_id/:product_id' => 'reports#report_view_monthly_products'
  match 'companies/reports/monthly_products/:company_id' => 'reports#report_monthly_products'
  match 'companies/reports/products/:company_id' => 'reports#report_products'
  match 'companies/reports/view_monthly_sellers/:company_id/:user_id' => 'reports#report_view_monthly_sellers'
  match 'companies/reports/monthly_sellers/:company_id' => 'reports#report_monthly_sellers'
  match 'companies/reports/sellers/:company_id' => 'reports#report_sellers'
  match 'companies/reports/monthly_sales/:company_id' => 'reports#report_monthly_sales'
  match 'companies/reports/sales/:company_id' => 'reports#report_sales'
  match 'companies/reports/:company_id' => 'reports#reports'

  match 'company_users/ac_users' => 'company_users#ac_users'
  match 'company_users/new/:company_id' => 'company_users#new'
  match 'companies/company_users/:company_id' => 'company_users#list_users'
  resources :company_users

  match 'invoice/add_kit/:company_id' => 'invoices#add_kit'
  match 'invoices/list_items/:company_id' => 'invoices#list_items'
  match 'invoices/ac_kit/:company_id' => 'invoices#ac_kit'
  match 'invoices/ac_products/:company_id' => 'invoices#ac_products'
  match 'invoices/ac_user/:company_id' => 'invoices#ac_user'
  match 'invoices/ac_customers/:company_id' => 'invoices#ac_customers'
  match 'invoices/new/:company_id' => 'invoices#new'
  match 'invoices/do_email/:id' => 'invoices#do_email'
  match 'invoices/do_process/:id' => 'invoices#do_process'
  match 'invoices/email/:id' => 'invoices#email'
  match 'invoices/pdf/:id' => 'invoices#pdf'
  match 'companies/invoices/:company_id' => 'invoices#list_invoices'
  resources :invoices

  match 'customers/create_ajax/:company_id' => 'customers#create_ajax'
  match 'customers/new/:company_id' => 'customers#new'
  match 'companies/customers/:company_id' => 'customers#list_customers'
  resources :customers

  match 'divisions/new/:company_id' => 'divisions#new'
  match 'companies/divisions/:company_id' => 'divisions#list_divisions'
  resources :divisions

  match 'restocks/process/:id' => 'restocks#do_process'
  match 'restocks/new/:company_id/:product_id' => 'restocks#new'
  match 'companies/restocks/:company_id/:product_id' => 'restocks#list_restocks'
  resources :restocks

  match 'products_kits/list_items/:company_id' => 'products_kits#list_items'
  match 'products_kits/new/:company_id' => 'products_kits#new'
  match 'companies/products_kits/:company_id' => 'products_kits#list_products_kits'
  resources :products_kits

  match 'products_categories/new/:company_id' => 'products_categories#new'
  match 'companies/products_categories/:company_id' => 'products_categories#list_products_categories'
  resources :products_categories

  match 'products/ac_products/:company_id' => 'products#ac_products'
  match 'products/ac_categories/:company_id' => 'products#ac_categories'
  match 'products/new/:company_id' => 'products#new'
  match 'companies/products/:company_id' => 'products#list_products'
  resources :products

  match 'suppliers/new/:company_id' => 'suppliers#new'
  match 'companies/suppliers/:company_id' => 'suppliers#list_suppliers'
  resources :suppliers

  match 'locations/new/:company_id' => 'locations#new'
  match 'companies/locations/:company_id' => 'locations#list_locations'
  resources :locations
  
  match 'companies/export/:id' => 'companies#export'
  resources :companies

  resources :users_packages

  match 'payment/:slug' => 'packages#payment'
  match 'pricing/:slug' => 'packages#pick_package'
  match 'pricing' => 'packages#pricing'
  resources :packages

  match 'p/:page_name' => 'pages#name_clean'
  match 'err_not_found' => 'pages#err_not_found'
  match 'quick_upload' => 'pages#quick_upload'
  resources :pages

  match 'err_perms' => 'users#err_perms'
  match 'register' => 'users#register'
  match 'logout' => 'users#logout'
  match 'login' => 'users#login'
  resources :users
  
  resources :sessions
  
  match 'dashboard' => 'pages#dashboard'
  root :to => "pages#frontpage"
  

end

app/models/products_category.rb
class ProductsCategory < ActiveRecord::Base
  self.per_page = 20
  
  validates_presence_of :company_id, :category
  
  belongs_to :company
end

app/controllers/products_categories_controller.rb
include UsersHelper
include CompaniesHelper

class ProductsCategoriesController < ApplicationController
  before_filter :checkLogin, :checkCompanies
  
  # List product categories for a company
  def list_products_categories
    @company = Company.find(params[:company_id])
    @pagetitle = "#{@company.name} - Product categories"
    
    if(@company.can_view(getUser()))
      @products_categories = ProductsCategory.paginate(:page => params[:page], :order => 'category', :conditions => {:company_id => @company.id})
    else
      errPerms()
    end
  end
  
  # GET /products_categories
  # GET /products_categories.xml
  def index
    @companies = Company.find(:all, :conditions => {:user_id => getUserId()}, :order => "name")
    @path = 'products_categories'
    @pagetitle = "Product categories"
  end

  # GET /products_categories/1
  # GET /products_categories/1.xml
  def show
    @products_category = ProductsCategory.find(params[:id])
    @pagetitle = "Product categories - #{@products_category.category}"
  end

  # GET /products_categories/new
  # GET /products_categories/new.xml
  def new
    @pagetitle = "New product category"
    @products_category = ProductsCategory.new
    @company = Company.find(params[:company_id])
    @products_category[:company_id] = @company.id
  end

  # GET /products_categories/1/edit
  def edit
    @pagetitle = "Edit product category"
    @products_category = ProductsCategory.find(params[:id])
    @company = Company.find(@products_category[:company_id])
    @products_category[:company_id] = @company.id
  end

  # POST /products_categories
  # POST /products_categories.xml
  def create
    @pagetitle = "New product category"
    @products_category = ProductsCategory.new(params[:products_category])

    respond_to do |format|
      if @products_category.save
        format.html { redirect_to(@products_category, :notice => 'Products category was successfully created.') }
        format.xml  { render :xml => @products_category, :status => :created, :location => @products_category }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @products_category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /products_categories/1
  # PUT /products_categories/1.xml
  def update
    @pagetitle = "Edit product category"
    @products_category = ProductsCategory.find(params[:id])

    respond_to do |format|
      if @products_category.update_attributes(params[:products_category])
        format.html { redirect_to(@products_category, :notice => 'Products category was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @products_category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /products_categories/1
  # DELETE /products_categories/1.xml
  def destroy
    @products_category = ProductsCategory.find(params[:id])
    company_id = @products_category[:company_id]
    @products_category.destroy

    respond_to do |format|
      format.html { redirect_to("/companies/products_categories/" + company_id.to_s) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/products_categories_helper.rb
module ProductsCategoriesHelper
end

app/views/products_categories/_form.html.erb
<%= form_for(@products_category) do |f| %>
  <% if @products_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@products_category.errors.count, "error") %> prohibited this products_category from being saved:</h2>

      <ul>
      <% @products_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.hidden_field :company_id %>
    <%= f.submit %>
  </div>
<% end %>

app/views/products_categories/_list.html.erb
<% if @products_categories.count > 0 %>
  <div class="products">
    <% for category in @products_categories %>
      <div class="item">
        <div class="title">
          <%= category.category %>
        </div>
        <div class="metadata">
          <%= link_to "Edit", edit_products_category_path(category) %> &#183;
          <%= link_to 'Delete', category, :confirm => 'Are you sure?', :method => :delete %>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <p class="error">
    You don't have any product categories yet.  You can <%= link_to "add one", "/products_categories/new/#{@company.id}" %>.
  </p>
<% end %>

app/views/products_categories/edit.html.erb
<div class="breadcrumbs">
  <%= link_to "My companies", "/companies" %> &raquo;
  <%= link_to @products_category.company.name, @products_category.company %> &raquo;
  <%= link_to "Product categories", "/companies/products_categories/#{@products_category.company.id}" %> &raquo;
  <%= link_to @products_category.category, "/products_categories/#{@products_category.id}" %>
</div>

<h1>
  <%= image_tag("product_category_48.png", :class => "vmiddle") %>
  Editing product category
</h1>

<%= render 'form' %>

<div class="button">
  <%= link_to 'Back', "/companies/products_categories/#{@products_category.company.id}" %>
</div>

app/views/products_categories/index.html.erb
<div class="breadcrumbs">
  <%= link_to "My companies", "/companies" %>
</div>

<h1>
  <%= image_tag("product_category_48.png", :class => "vmiddle") %>
  Product categories
</h1>

<p>
  Select one of your companies to view its product categories:
</p>

<%= render "companies/list_select" %>

app/views/products_categories/list_products_categories.html.erb
<div class="breadcrumbs">
  <%= link_to "My companies", "/companies" %> &raquo;
  <%= link_to @company.name, @company %>
</div>

<h1>
  <%= image_tag("product_category_48.png", :class => "vmiddle") %>
  Product categories
</h1>

<%= render "products_categories/list" %>

<br />

<div class="button">
  <%= link_to 'New Product Category', "/products_categories/new/#{@company.id}" %>
</div>

<br />

<%= will_paginate @products_categories %>

app/views/products_categories/new.html.erb
<div class="breadcrumbs">
  <%= link_to "My companies", "/companies" %> &raquo;
  <%= link_to @company.name, @company %> &raquo;
  <%= link_to "Product categories", products_categories_path %>
</div>

<h1>
  <%= image_tag("product_category_48.png", :class => "vmiddle") %>
  New product category
</h1>

<%= render 'form' %>

<div class="button">
  <%= link_to 'Back', "/companies/products_categories/#{@company.id}" %>
</div>

app/views/products_categories/show.html.erb
<div class="breadcrumbs">
  <%= link_to "My companies", "/companies" %> &raquo;
  <%= link_to @products_category.company.name, @products_category.company %> &raquo;
  <%= link_to "Product categories", "/companies/products_categories/#{@products_category.company.id}" %>
</div>

<h1>
  <%= image_tag("product_category_48.png", :class => "vmiddle") %>
  <%= @products_category.category %>
</h1>

<br />

<div class="button">
  <%= link_to 'Edit', edit_products_category_path(@products_category) %>
  <%= link_to 'Back', "/companies/products_categories/#{@products_category.company.id}" %>
</div>