config/routes.rb
Mnygo::Application.routes.draw do
  match 'companies/reports/monthly_profits/:company_id' => 'reports#monthly_profits'
  match 'companies/reports/profits/:company_id' => 'reports#profits'
  match 'companies/reports/view_monthly_divisions/:company_id/:division_id' => 'reports#report_view_monthly_divisions'
  match 'companies/reports/monthly_divisions/:company_id' => 'reports#report_monthly_divisions'
  match 'companies/reports/divisions/:company_id' => 'reports#report_divisions'
  match 'companies/reports/view_monthly_locations/:company_id/:location_id' => 'reports#report_view_monthly_locations'
  match 'companies/reports/monthly_locations/:company_id' => 'reports#report_monthly_locations'
  match 'companies/reports/locations/:company_id' => 'reports#report_locations'
  match 'companies/reports/view_monthly_customers/:company_id/:customer_id' => 'reports#report_view_monthly_customers'
  match 'companies/reports/monthly_customers/:company_id' => 'reports#report_monthly_customers'
  match 'companies/reports/customers/:company_id' => 'reports#report_customers'
  match 'companies/reports/view_monthly_products/:company_id/:product_id' => 'reports#report_view_monthly_products'
  match 'companies/reports/monthly_products/:company_id' => 'reports#report_monthly_products'
  match 'companies/reports/products/:company_id' => 'reports#report_products'
  match 'companies/reports/view_monthly_sellers/:company_id/:user_id' => 'reports#report_view_monthly_sellers'
  match 'companies/reports/monthly_sellers/:company_id' => 'reports#report_monthly_sellers'
  match 'companies/reports/sellers/:company_id' => 'reports#report_sellers'
  match 'companies/reports/monthly_sales/:company_id' => 'reports#report_monthly_sales'
  match 'companies/reports/sales/:company_id' => 'reports#report_sales'
  match 'companies/reports/:company_id' => 'reports#reports'

  match 'company_users/ac_users' => 'company_users#ac_users'
  match 'company_users/new/:company_id' => 'company_users#new'
  match 'companies/company_users/:company_id' => 'company_users#list_users'
  resources :company_users

  match 'invoice/add_kit/:company_id' => 'invoices#add_kit'
  match 'invoices/list_items/:company_id' => 'invoices#list_items'
  match 'invoices/ac_kit/:company_id' => 'invoices#ac_kit'
  match 'invoices/ac_products/:company_id' => 'invoices#ac_products'
  match 'invoices/ac_user/:company_id' => 'invoices#ac_user'
  match 'invoices/ac_customers/:company_id' => 'invoices#ac_customers'
  match 'invoices/new/:company_id' => 'invoices#new'
  match 'invoices/do_email/:id' => 'invoices#do_email'
  match 'invoices/do_process/:id' => 'invoices#do_process'
  match 'invoices/email/:id' => 'invoices#email'
  match 'invoices/pdf/:id' => 'invoices#pdf'
  match 'companies/invoices/:company_id' => 'invoices#list_invoices'
  resources :invoices

  match 'customers/create_ajax/:company_id' => 'customers#create_ajax'
  match 'customers/new/:company_id' => 'customers#new'
  match 'companies/customers/:company_id' => 'customers#list_customers'
  resources :customers

  match 'divisions/new/:company_id' => 'divisions#new'
  match 'companies/divisions/:company_id' => 'divisions#list_divisions'
  resources :divisions

  match 'restocks/process/:id' => 'restocks#do_process'
  match 'restocks/new/:company_id/:product_id' => 'restocks#new'
  match 'companies/restocks/:company_id/:product_id' => 'restocks#list_restocks'
  resources :restocks

  match 'products_kits/list_items/:company_id' => 'products_kits#list_items'
  match 'products_kits/new/:company_id' => 'products_kits#new'
  match 'companies/products_kits/:company_id' => 'products_kits#list_products_kits'
  resources :products_kits

  match 'products_categories/new/:company_id' => 'products_categories#new'
  match 'companies/products_categories/:company_id' => 'products_categories#list_products_categories'
  resources :products_categories

  match 'products/ac_products/:company_id' => 'products#ac_products'
  match 'products/ac_categories/:company_id' => 'products#ac_categories'
  match 'products/new/:company_id' => 'products#new'
  match 'companies/products/:company_id' => 'products#list_products'
  resources :products

  match 'suppliers/new/:company_id' => 'suppliers#new'
  match 'companies/suppliers/:company_id' => 'suppliers#list_suppliers'
  resources :suppliers

  match 'locations/new/:company_id' => 'locations#new'
  match 'companies/locations/:company_id' => 'locations#list_locations'
  resources :locations
  
  match 'companies/export/:id' => 'companies#export'
  resources :companies

  resources :users_packages

  match 'payment/:slug' => 'packages#payment'
  match 'pricing/:slug' => 'packages#pick_package'
  match 'pricing' => 'packages#pricing'
  resources :packages

  match 'p/:page_name' => 'pages#name_clean'
  match 'err_not_found' => 'pages#err_not_found'
  match 'quick_upload' => 'pages#quick_upload'
  resources :pages

  match 'err_perms' => 'users#err_perms'
  match 'register' => 'users#register'
  match 'logout' => 'users#logout'
  match 'login' => 'users#login'
  resources :users
  
  resources :sessions
  
  match 'dashboard' => 'pages#dashboard'
  root :to => "pages#frontpage"
  

end

app/models/company_user.rb
class CompanyUser < ActiveRecord::Base
  validates_presence_of :company_id, :user_id
  
  belongs_to :company
  belongs_to :user
end

app/controllers/company_users_controller.rb
include UsersHelper

class CompanyUsersController < ApplicationController
  before_filter :checkLogin
  
  # Autocomplete users
  def ac_users
    @users = User.find(:all, :conditions => ["username LIKE ? OR email LIKE ?", "%" + params[:q] + "%", "%" + params[:q] + "%"])
   
    render :layout => false
  end
  
  # List company users
  def list_users
    @company = Company.find(params[:company_id])
    @pagetitle = "#{@company.name} - Locations"
  
    if(@company.can_view(getUser()))
      @company_users = CompanyUser.find(:all, :conditions => {:company_id => @company.id})
    else
      errPerms()
    end
  end
  
  # GET /company_users
  # GET /company_users.xml
  def index
    @company_users = CompanyUser.all
  end

  # GET /company_users/1
  # GET /company_users/1.xml
  def show
    @company_user = CompanyUser.find(params[:id])
  end

  # GET /company_users/new
  # GET /company_users/new.xml
  def new
    @company_user = CompanyUser.new
    @company = Company.find(params[:company_id])
    @company_user[:company_id] = @company[:id]
    
    # Check package limits
    @users_left_i = getUser().users_left
    @users_left = getUser().print_users_left
    @users_left_class = getUser().users_left_class
  end

  # GET /company_users/1/edit
  def edit
    @company_user = CompanyUser.find(params[:id])
  end

  # POST /company_users
  # POST /company_users.xml
  def create
    @company_user = CompanyUser.new(params[:company_user])
    @company = Company.find(params[:company_user][:company_id])
    
    @users_left_i = getUser().users_left
    @users_left = getUser().print_users_left
    @users_left_class = getUser().users_left_class
    
    # Check package limits
    if(@users_left_i <= 0 and @users_left_i > -1000)
      flash[:error] = "You have created the most users you can within your package.  Please select another package to create more users."
      redirect_to("/pricing")
    else
      if(params[:company_user][:user_id] and params[:company_user][:user_id] != "")
        # Check if user already exists for the company
        @alr_user = CompanyUser.find(:first, :conditions => {:company_id => @company.id, :user_id => params[:company_user][:user_id]})

        if(@alr_user)
          err_alr = true
        end
      end

      if(err_alr)
        flash[:error] = "This user is already part of the company"
        redirect_to "/company_users/new/#{@company.id}"
      elsif @company_user.save
        redirect_to(@company_user, :notice => 'Company user was successfully created.')
      else
        render :action => "new"
      end
    end
  end

  # PUT /company_users/1
  # PUT /company_users/1.xml
  def update
    @company_user = CompanyUser.find(params[:id])

    respond_to do |format|
      if @company_user.update_attributes(params[:company_user])
        format.html { redirect_to(@company_user, :notice => 'Company user was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @company_user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /company_users/1
  # DELETE /company_users/1.xml
  def destroy
    @company_user = CompanyUser.find(params[:id])
    company_id = @company_user[:company_id]
    @company = @company_user.company
    
    # Check if we can delete the user
    if(@company_user.user_id != @company.user_id)
      @company_user.destroy
    else
      flash[:error] = "You cannot delete the company creator from the company."
    end
    
    redirect_to("/companies/company_users/" + company_id.to_s)
  end
end

app/helpers/company_users_helper.rb
module CompanyUsersHelper
end

app/views/company_users/_form.html.erb
<%= form_for(@company_user) do |f| %>
  <% if @company_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company_user.errors.count, "error") %> prohibited this company_user from being saved:</h2>

      <ul>
      <% @company_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <label for="ac_user" class="bold">User*</label><br />
    <input type="text" name="ac_user" id="ac_user" value="" />
    <div class="small">
      Search for an user using his/her username or email to add it to your company.
    </div>
    <br />
    <div>
      <strong>Selected user:</strong>
      <span id="curr_selected_user"><!-- i --></span>
    </div>
  </div>
  <div class="actions">
    <%= f.hidden_field :user_id %>
    <%= f.hidden_field :company_id %>
    <%= f.submit %>
  </div>
<% end %>

<%= render 'layouts/autocomplete' %>

<script type="text/javascript">
  $(document).ready(function() {
    $("#ac_user").autocomplete("/company_users/ac_users", {
			matchSubset: 1,
			matchContains: 1,
      selectFirst: false
    });
    
    $("#ac_user").result(function(event, data, formatted) {
      $("#company_user_user_id").val(data[2]);
      $("#curr_selected_user").html(data[0]);
    });
  });
</script>

app/views/company_users/_list.html.erb
<% if @company_users.count > 0 %>
  <div class="company_users">
    <% for company_user in @company_users %>
      <div class="item">
        <div class="title">
          <%= link_to company_user.user.username, company_user %>
        </div>
        <div class="metadata">
          <%= link_to "View", company_user %> &#183;
          <% if(@company.user_id != company_user.user_id) %>
            <%= link_to 'Delete', company_user, :confirm => 'Are you sure?', :method => :delete %>
          <% else %>
            <abbr class="linethrough" title="You cannot delete the company creator">Delete</abbr>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <p class="error">
    You don't have any users for your company yet.  You can <%= link_to "add one", "/company_users/new/#{@company.id}" %>.
  </p>
<% end %>

app/views/company_users/ac_users.html.erb
<% if @users %>
  <% for user in @users %>
    <%= user.username %>|BRK|<%= user.id %>
  <% end %>
<% end %>

app/views/company_users/edit.html.erb
<div class="breadcrumbs">
  <%= link_to "My companies", "/companies" %> &raquo;
  <%= link_to @company_user.company.name, @company_user.company %> &raquo;
  <%= link_to "Company userss", "/companies/company_users/#{@company_user.company.id}" %> &raquo;
  <%= link_to @company_user.user.username, @company_user %>
</div>

<h1>
  <%= image_tag("employees_48.png", :class => "vmiddle") %>
  Edit company user
</h1>

<p>
  To modify the company user, please fill out the following form.  Fields marked with <strong>*</strong> are required.
</p>
<%= render 'form' %>

<div class="button">
  <%= link_to 'Show', @company_user %>
  <%= link_to 'Back', "/companies/company_users/#{@company_user.company.id}" %>
</div>

app/views/company_users/index.html.erb
<h1>Listing company_users</h1>

<table>
  <tr>
    <th>Company</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @company_users.each do |company_user| %>
  <tr>
    <td><%= company_user.company_id %></td>
    <td><%= company_user.user_id %></td>
    <td><%= link_to 'Show', company_user %></td>
    <td><%= link_to 'Edit', edit_company_user_path(company_user) %></td>
    <td><%= link_to 'Destroy', company_user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Company user', new_company_user_path %>

app/views/company_users/list_users.html.erb
<div class="breadcrumbs">
  <%= link_to "My companies", "/companies" %> &raquo;
  <%= link_to @company.name, @company %>
</div>

<h1>
  <%= image_tag("employees_48.png", :class => "vmiddle") %>
  Users
</h1>

<%= render "company_users/list" %>

<br />

<div class="button">
  <%= link_to 'New Company User', "/company_users/new/#{@company.id}" %>
</div>

app/views/company_users/new.html.erb
<div class="breadcrumbs">
  <%= link_to "My companies", "/companies" %> &raquo;
  <%= link_to @company.name, @company %> &raquo;
  <%= link_to "Company users", "/companies/company_users/#{@company.id}" %>
</div>

<h1>
  <%= image_tag("employees_48.png", :class => "vmiddle") %>
  New company user
</h1>

<div class="<%= @users_left_class %>">
  You can create <%= @users_left %> more users.
  <% if @users_left_i <= 0 and @users_left_i != -1000 %>
    If you want to create more users, please <%= link_to "select another package", "/pricing" %>.
  <% end %>
</div>

<p>
  To a new user to your company, please fill out the following form.  Fields marked with <strong>*</strong> are required.
</p>

<%= render 'form' %>

<div class="button">
  <%= link_to 'Back', "/companies/company_users/#{@company.id}" %>
</div>

app/views/company_users/show.html.erb
<div class="breadcrumbs">
  <%= link_to "My companies", "/companies" %> &raquo;
  <%= link_to @company_user.company.name, @company_user.company %> &raquo;
  <%= link_to "Company users", "/companies/company_users/#{@company_user.company.id}" %>
</div>

<h1>
  <%= image_tag("employees_48.png", :class => "vmiddle") %>
  <%= @company_user.user.username %>
</h1>

<p>
  <b>Company:</b>
  <%= link_to @company_user.company.name, @company_user.company %>
</p>

<p>
  <b>User:</b>
  <%= link_to @company_user.user.username, @company_user.user %>
</p>

<div class="button">
  <%= link_to 'Back', "/companies/company_users/#{@company_user.company.id}" %>
</div>